### ISSUE TITLE
Feature request, run in demo mode with just in memory datasource

### ISSUE THREAD

**Issue by alkemann** [finn-no/unleash-client-java#16]
To be able to try it and see how it work, it would be great to be able to just run it with out needing to set up the database.

**Comment by ivarconr** [comment]
Thanks for your request! Currently in the java-client we provide 2 options for you:

1. Within the client we already provide a `FakeUnleash` implementation, mostly to facilitate unit-testing: https://github.com/finn-no/unleash-client-java/blob/master/src/main/java/no/finn/unleash/FakeUnleash.java

2. Feel free to use the openly deployed cloud demo for local testing:
http://unleash.herokuapp.com/

If you want the server to be able to run in in-memory mode it would be better to post your request on the [unleash project on github](https://github.com/finn-no/unleash)

**Comment by alkemann** [comment]
Ops i actually meant this for the actual unleash node app, not the java client, but yes that point two there answers my request i guess. Include it in the readme of the main repo maybe? :D
