### ISSUE TITLE
Strategy for strategies

### ISSUE THREAD

**Issue by Andersos** [finn-no/unleash-client-java#18]
Unleash has gotten some pull requests to the Finn client and it is good that people want to use the service. I just want to raise a concern.

Right now this version has the following strategies:
- DefaultStrategy
- UnknownStrategy

Finn client has the following strategies:
- ActiveForUserWithIdStrategy
- BetaUserStrategy
- ByHostNameStrategy
- GradualRolloutRandomStrategy
- RemoteAddrStrategy

Should we not move more of the strategies from the Finn client over to the open source one?

I also suggest that we add a markdown file that describes the strategies with example use cases.

**Comment by ivarconr** [comment]
This is exactly what we must plan for. Can you organize a short meeting to
let us to discuss this?

**Comment by Andersos** [comment]
Sounds like a good idea. We should also see if we could put other issues on the agenda like "User authentication" https://github.com/finn-no/unleash/issues/33 and "Integration tests" https://github.com/finn-no/unleash/issues/32

**Comment by Andersos** [comment]
Meeting scheduled for wednesday 25. februar 2015 12:00-13:00.

**Comment by Andersos** [comment]
Some notes from the meeting

### Unleash status
Many have started using Unleash.
@ivarconr has presented Unleash and Feature Toggles on the [Architecture summit](http://tech.finn.no/2015/02/10/summit/) [here](https://vimeo.com/finnlabs/review/118005763/8fe264322d) and [Smidig 2014](http://2014.smidig.no/) [here](https://vimeo.com/110736837).

We will try to write something on the [tech blog](http://tech.finn.no/) about Unleash.

I will try and do a write-up of how to setup a local database on Mac.
Pg_vertualenv is working fine on Linux. Do we need to document how to do this?
Maybe @eirslett can come with some pointer about how to run Unleash locally on Windows.

### [User authentication](https://github.com/finn-no/unleash/issues/33) 
You should always be able to turn on or off toggles even if the authentication provider is down.
Ideally everyone that dose a change need to be logged by name.
We will investigate using basic auth and having Crowd as the user provider.

### [Strategy for strategies](https://github.com/finn-no/unleash-client-java/issues/18)

It’s a good idea to first implement the strategies in the Finn client and later move them to the Open Source client when they are mature.
The idea is to deprecate good strategies in the Finn client and move them over to the this repo.

### Integration tests
For now we are pleased with the amount of tests and will this issue for now
https://github.com/finn-no/unleash/issues/32 

### Other
We are looking into making a Node client for Unleash. @ivarconr is leading the push for this.
