### ISSUE TITLE
Problem with userWithId strategy

### ISSUE THREAD

**Issue by Andersos** [finn-no/unleash-client-java#19]
I'm putting this here even thought it relates to the Finn client.
There was additional whitespace after an id in the parameter so it didn't match.
We should maybe remove whitespace from the parameters?
This might effect more than just the userWithId strategy.

![skjermbilde 2015-03-05 kl 17 07 03](https://cloud.githubusercontent.com/assets/288977/6508593/0f4b15dc-c35a-11e4-8203-e164d6fad78a.png)

**Comment by ivarconr** [comment]
Is this up to the unleash-server to decide, or should it be handled in the strategy implementations? 

PS! We are trimming trailing spaces in the admin-GUI.

**Comment by Andersos** [comment]
If we are trimming trailing spaces in the admin-GUI is it being trimmed per element in the list?
I think this should be solved before it is persisted so maybe the issue is with Unleash-server?

**Comment by ivarconr** [comment]
but then unleash has to know that the property is a comma separated list?

**Comment by Andersos** [comment]
Not nessescarily. We can just removing whitespace on all data. But maybe we should also handle it in the client.

**Comment by ivarconr** [comment]
true. Will this work for all our existing strategies?

**Comment by Andersos** [comment]
I'm not sure we want to do it. It might have adverse effects. We should maybe start with handeling whitespace for that strategy. Ideally this should also be solved broader than on a per strategy basis maybe?

Will there be strategies that need or want whitespace in their data?

**Comment by sveinelo** [comment]
Yes, there wil be strategies that want whitespace in their configuration, but not in a comma separated JSON array I guess.

**Comment by ivarconr** [comment]
can you give an example @sveinelo ?

**Comment by sveinelo** [comment]
{"key":"value with whitespace"}

**Comment by ivarconr** [comment]
I was thinking about what kind of strategy?

**Comment by sveinelo** [comment]
EnabledForAdTitlesWithWhiteSpaceInTitleStrategy , my point is that we don't know what kind of strategies will come in the future, and therefore we should not strip out all whitespace from the configuration parameters. Not inside JSON strings at least.

**Comment by ivarconr** [comment]
Thanks, you make a reasonable argument. 

It is also intended for that strategy parameters can have different types. Now all we support are strings. Later we shall provide other parameter-types, such as JSON.
