### ISSUE TITLE
Plugin Api to registrer custom strategies

### ISSUE THREAD

**Issue by torarnek** [finn-no/unleash-client-java#21]
It would have been nice with the a possibility to add strategies at runtime. E.g. adding the following addStrategy method:
 
interface Unlesh{
   boolean isEnabled(String toggleName);
    boolean isEnabled(String toggleName, boolean defaultSetting);
    **addStrategy(Strategy strategy);**
}

**Comment by sveinelo** [comment]
What is the use case for this? New strategies can be added when you create an instance of Unleash.

```public DefaultUnleash(URI unleashServer, Strategy... strategies) {
    ...
}
```

**Comment by ivarconr** [comment]
+1 on a real example on why this would be useful.

**Comment by torarnek** [comment]
Yes, it is not needed at runtime, specifying strategies for DefaultUnleash is sufficient. Thanks.
